/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/_index': RouteRecordInfo<'/_index', '/_index', Record<never, never>, Record<never, never>>,
    '/[...NotFound]': RouteRecordInfo<'/[...NotFound]', '/:NotFound(.*)', { NotFound: ParamValue<true> }, { NotFound: ParamValue<false> }>,
    '/[oid]/': RouteRecordInfo<'/[oid]/', '/:oid', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/calculationEmployee': RouteRecordInfo<'/[oid]/calculationEmployee', '/:oid/calculationEmployee', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/dispatcherPerformance': RouteRecordInfo<'/[oid]/dispatcherPerformance', '/:oid/dispatcherPerformance', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/expensesView': RouteRecordInfo<'/[oid]/expensesView', '/:oid/expensesView', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/hrWindow': RouteRecordInfo<'/[oid]/hrWindow', '/:oid/hrWindow', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/insurance/[id]': RouteRecordInfo<'/[oid]/insurance/[id]', '/:oid/insurance/:id', { oid: ParamValue<true>, id: ParamValue<true> }, { oid: ParamValue<false>, id: ParamValue<false> }>,
    '/[oid]/journals/checkOut': RouteRecordInfo<'/[oid]/journals/checkOut', '/:oid/journals/checkOut', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/journals/dispatcherView': RouteRecordInfo<'/[oid]/journals/dispatcherView', '/:oid/journals/dispatcherView', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/journals/factoring_journal': RouteRecordInfo<'/[oid]/journals/factoring_journal', '/:oid/journals/factoring_journal', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/journals/incomeView': RouteRecordInfo<'/[oid]/journals/incomeView', '/:oid/journals/incomeView', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/journals/quickPay': RouteRecordInfo<'/[oid]/journals/quickPay', '/:oid/journals/quickPay', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/me': RouteRecordInfo<'/[oid]/me', '/:oid/me', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/order/[id]': RouteRecordInfo<'/[oid]/order/[id]', '/:oid/order/:id', { oid: ParamValue<true>, id: ParamValue<true> }, { oid: ParamValue<false>, id: ParamValue<false> }>,
    '/[oid]/order/all': RouteRecordInfo<'/[oid]/order/all', '/:oid/order/all', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/order/create': RouteRecordInfo<'/[oid]/order/create', '/:oid/order/create', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/order/dispatcher': RouteRecordInfo<'/[oid]/order/dispatcher', '/:oid/order/dispatcher', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/paymentsAndExpenses/finesOfEmployee': RouteRecordInfo<'/[oid]/paymentsAndExpenses/finesOfEmployee', '/:oid/paymentsAndExpenses/finesOfEmployee', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/paymentsAndExpenses/owner_expenses': RouteRecordInfo<'/[oid]/paymentsAndExpenses/owner_expenses', '/:oid/paymentsAndExpenses/owner_expenses', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/paymentsAndExpenses/ownerPayments': RouteRecordInfo<'/[oid]/paymentsAndExpenses/ownerPayments', '/:oid/paymentsAndExpenses/ownerPayments', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/paymentsAndExpenses/paymentsToDispatchers': RouteRecordInfo<'/[oid]/paymentsAndExpenses/paymentsToDispatchers', '/:oid/paymentsAndExpenses/paymentsToDispatchers', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/paymentsAndExpenses/settlements_to_employee': RouteRecordInfo<'/[oid]/paymentsAndExpenses/settlements_to_employee', '/:oid/paymentsAndExpenses/settlements_to_employee', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/paymentsView': RouteRecordInfo<'/[oid]/paymentsView', '/:oid/paymentsView', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/referenceBooks': RouteRecordInfo<'/[oid]/referenceBooks', '/:oid/referenceBooks', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/refs/brokers': RouteRecordInfo<'/[oid]/refs/brokers', '/:oid/refs/brokers', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/refs/drivers': RouteRecordInfo<'/[oid]/refs/drivers', '/:oid/refs/drivers', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/refs/insurances': RouteRecordInfo<'/[oid]/refs/insurances', '/:oid/refs/insurances', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/refs/organizations': RouteRecordInfo<'/[oid]/refs/organizations', '/:oid/refs/organizations', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/refs/owners': RouteRecordInfo<'/[oid]/refs/owners', '/:oid/refs/owners', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/refs/statuses': RouteRecordInfo<'/[oid]/refs/statuses', '/:oid/refs/statuses', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/refs/users': RouteRecordInfo<'/[oid]/refs/users', '/:oid/refs/users', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/refs/vehicles': RouteRecordInfo<'/[oid]/refs/vehicles', '/:oid/refs/vehicles', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/reports/dispatcherReport': RouteRecordInfo<'/[oid]/reports/dispatcherReport', '/:oid/reports/dispatcherReport', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/reports/ownerReport': RouteRecordInfo<'/[oid]/reports/ownerReport', '/:oid/reports/ownerReport', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/[oid]/reportsView': RouteRecordInfo<'/[oid]/reportsView', '/:oid/reportsView', { oid: ParamValue<true> }, { oid: ParamValue<false> }>,
    '/organisation': RouteRecordInfo<'/organisation', '/organisation', Record<never, never>, Record<never, never>>,
    '/tracking': RouteRecordInfo<'/tracking', '/tracking', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/_index.vue': {
      routes: '/_index'
      views: never
    }
    'src/pages/[...NotFound].vue': {
      routes: '/[...NotFound]'
      views: never
    }
    'src/pages/[oid]/index.vue': {
      routes: '/[oid]/'
      views: never
    }
    'src/pages/[oid]/calculationEmployee.vue': {
      routes: '/[oid]/calculationEmployee'
      views: never
    }
    'src/pages/[oid]/dispatcherPerformance.vue': {
      routes: '/[oid]/dispatcherPerformance'
      views: never
    }
    'src/pages/[oid]/expensesView.vue': {
      routes: '/[oid]/expensesView'
      views: never
    }
    'src/pages/[oid]/hrWindow.vue': {
      routes: '/[oid]/hrWindow'
      views: never
    }
    'src/pages/[oid]/insurance/[id].vue': {
      routes: '/[oid]/insurance/[id]'
      views: never
    }
    'src/pages/[oid]/journals/checkOut.vue': {
      routes: '/[oid]/journals/checkOut'
      views: never
    }
    'src/pages/[oid]/journals/dispatcherView.vue': {
      routes: '/[oid]/journals/dispatcherView'
      views: never
    }
    'src/pages/[oid]/journals/factoring_journal.vue': {
      routes: '/[oid]/journals/factoring_journal'
      views: never
    }
    'src/pages/[oid]/journals/incomeView.vue': {
      routes: '/[oid]/journals/incomeView'
      views: never
    }
    'src/pages/[oid]/journals/quickPay.vue': {
      routes: '/[oid]/journals/quickPay'
      views: never
    }
    'src/pages/[oid]/me.vue': {
      routes: '/[oid]/me'
      views: never
    }
    'src/pages/[oid]/order/[id].vue': {
      routes: '/[oid]/order/[id]'
      views: never
    }
    'src/pages/[oid]/order/all.vue': {
      routes: '/[oid]/order/all'
      views: never
    }
    'src/pages/[oid]/order/create.vue': {
      routes: '/[oid]/order/create'
      views: never
    }
    'src/pages/[oid]/order/dispatcher.vue': {
      routes: '/[oid]/order/dispatcher'
      views: never
    }
    'src/pages/[oid]/paymentsAndExpenses/finesOfEmployee.vue': {
      routes: '/[oid]/paymentsAndExpenses/finesOfEmployee'
      views: never
    }
    'src/pages/[oid]/paymentsAndExpenses/owner_expenses.vue': {
      routes: '/[oid]/paymentsAndExpenses/owner_expenses'
      views: never
    }
    'src/pages/[oid]/paymentsAndExpenses/ownerPayments.vue': {
      routes: '/[oid]/paymentsAndExpenses/ownerPayments'
      views: never
    }
    'src/pages/[oid]/paymentsAndExpenses/paymentsToDispatchers.vue': {
      routes: '/[oid]/paymentsAndExpenses/paymentsToDispatchers'
      views: never
    }
    'src/pages/[oid]/paymentsAndExpenses/settlements_to_employee.vue': {
      routes: '/[oid]/paymentsAndExpenses/settlements_to_employee'
      views: never
    }
    'src/pages/[oid]/paymentsView.vue': {
      routes: '/[oid]/paymentsView'
      views: never
    }
    'src/pages/[oid]/referenceBooks.vue': {
      routes: '/[oid]/referenceBooks'
      views: never
    }
    'src/pages/[oid]/refs/brokers.vue': {
      routes: '/[oid]/refs/brokers'
      views: never
    }
    'src/pages/[oid]/refs/drivers.vue': {
      routes: '/[oid]/refs/drivers'
      views: never
    }
    'src/pages/[oid]/refs/insurances.vue': {
      routes: '/[oid]/refs/insurances'
      views: never
    }
    'src/pages/[oid]/refs/organizations.vue': {
      routes: '/[oid]/refs/organizations'
      views: never
    }
    'src/pages/[oid]/refs/owners.vue': {
      routes: '/[oid]/refs/owners'
      views: never
    }
    'src/pages/[oid]/refs/statuses.vue': {
      routes: '/[oid]/refs/statuses'
      views: never
    }
    'src/pages/[oid]/refs/users.vue': {
      routes: '/[oid]/refs/users'
      views: never
    }
    'src/pages/[oid]/refs/vehicles.vue': {
      routes: '/[oid]/refs/vehicles'
      views: never
    }
    'src/pages/[oid]/reports/dispatcherReport.vue': {
      routes: '/[oid]/reports/dispatcherReport'
      views: never
    }
    'src/pages/[oid]/reports/ownerReport.vue': {
      routes: '/[oid]/reports/ownerReport'
      views: never
    }
    'src/pages/[oid]/reportsView.vue': {
      routes: '/[oid]/reportsView'
      views: never
    }
    'src/pages/organisation.vue': {
      routes: '/organisation'
      views: never
    }
    'src/pages/tracking.vue': {
      routes: '/tracking'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
